export const status = {
    RFQ_VERIFICATION_PENDING: "RFQ VERIFICATION PENDING",
    PROPOSAL_PENDING: "PROPOSAL PENDING",
    PROPOSAL_ACCEPTED: "PROPOSAL ACCEPTED",
    SAMPLING_REQUESTED: "SAMPLING REQUESTED",
    APPROVED: "APPROVED"
}